service: wicket-fastapi

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  stage: ${opt:stage, "dev"}
  layers:
    - ${cf:dbutils-layer-dev.DbutilsLayerExport}
    - { Ref: PythonRequirementsLambdaLayer }

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

custom:
  pythonRequirements:
    layer:
      name: requirements-layer
      description: Requirements
      compatibleRuntimes:
        - python3.9
#  customDomain:
#    domainName: YOUR_DOMAIN_HERE
#    stage: ${self:provider.stage}
#    certificateArn: YOUR_CERTIFICATE_ARN_HERE
#    endpointType: "edge"
#    securityPolicy: tls_1_2
#    apiType: rest
#    autoDomain: true
#    autoDomainWaitFor: 120

functions:
  api:
    package:
      patterns:
        - "main.py"
        - "!requirements.txt"
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!.venv/**"
        - "!node_modules/**"
        - "!layers/**"
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: any
          path: /
      - http:
          method: any
          path: /{proxy+}
