service: wicket-fastapi

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer:
      name: requirements-layer
      description: Requirements
      compatibleRuntimes:
        - python3.8

functions:
  api:
    package:
      patterns:
        - "main.py"
        - "!requirements.txt"
        - "!package.json"
        - "!package-lock.json"
        - "!.serverless/**"
        - "!.virtualenv/**"
        - "!node_modules/**"
    handler: main.handler
    environment:
      STAGE: ${self:provider.stage}
    layers:
      - ${cf:psycopg239-layer-dev.Psycopg239LayerExport}
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /
      - http:
          method: any
          path: /{proxy+}
